Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultContextTimeout: 60
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/upload
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 #5MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
DataBase:
  DBType: mysql
  Username: root
  Password: 12345678
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: eddycjy
  Issuer: blog_service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 969347529@qq.com
  Password:
  IsSSL: true
  Form: 969347529@qq.com
  To:
    - 2051921327@qq.com
